// Generated by CoffeeScript 1.9.2
(function() {
  var input, lookAndSay;

  input = "3113322113";

  input = input.split('');

  lookAndSay = function(input) {
    var count, digit, i, index, len, nextInput, previous, value;
    previous = void 0;
    count = 0;
    value = 0;
    nextInput = "";
    index = 1;
    for (i = 0, len = input.length; i < len; i++) {
      digit = input[i];
      if (digit === previous) {
        count++;
      } else {
        if (count !== 0) {
          nextInput += count + value;
        }
        count = 1;
        value = digit;
      }
      previous = digit;
      if (index === input.length) {
        nextInput += count + value;
      }
      index++;
    }
    console.log("nextInput.length", nextInput.length);
    return nextInput;
  };

  lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(lookAndSay(input))))))))))))))))))))))))))))))))))))))))))))))))));

}).call(this);
