// Generated by CoffeeScript 1.9.2
(function() {
  var flySpeed, flyTime, i, ignore, j, len, maxKm, name, r, ref, reindeer, reindeerArray, reindeerString, reindeerString2, restTime, ride2, time, timeToTravel, timeToTravel2;

  reindeerString = "Dancer can fly 27 km/s for 5 seconds, but then must rest for 132 seconds. Cupid can fly 22 km/s for 2 seconds, but then must rest for 41 seconds. Rudolph can fly 11 km/s for 5 seconds, but then must rest for 48 seconds. Donner can fly 28 km/s for 5 seconds, but then must rest for 134 seconds. Dasher can fly 4 km/s for 16 seconds, but then must rest for 55 seconds. Blitzen can fly 14 km/s for 3 seconds, but then must rest for 38 seconds. Prancer can fly 3 km/s for 21 seconds, but then must rest for 40 seconds. Comet can fly 18 km/s for 6 seconds, but then must rest for 103 seconds. Vixen can fly 18 km/s for 5 seconds, but then must rest for 84 seconds";

  reindeerString2 = "Comet can fly 14 km/s for 10 seconds, but then must rest for 127 seconds. Dancer can fly 16 km/s for 11 seconds, but then must rest for 162 seconds";

  reindeer = {};

  time = 0;

  timeToTravel = 2503;

  timeToTravel2 = 1000;

  reindeerArray = reindeerString.split('. ');

  for (j = 0, len = reindeerArray.length; j < len; j++) {
    r = reindeerArray[j];
    ref = r.split(' '), name = ref[0], ignore = ref[1], ignore = ref[2], flySpeed = ref[3], ignore = ref[4], ignore = ref[5], flyTime = ref[6], ignore = ref[7], ignore = ref[8], ignore = ref[9], ignore = ref[10], ignore = ref[11], ignore = ref[12], restTime = ref[13], ignore = ref[14];
    reindeer[name] = {
      flySpeed: parseInt(flySpeed),
      flyTime: parseInt(flyTime),
      restTime: parseInt(restTime),
      timeFlying: 0,
      timeResting: 0,
      km: 0,
      points: 0
    };
  }

  ride2 = function(reindeer) {
    if (reindeer.timeFlying < reindeer.flyTime) {
      reindeer.km += reindeer.flySpeed;
      return reindeer.timeFlying++;
    } else {
      if (reindeer.timeResting < reindeer.restTime) {
        reindeer.timeResting++;
      }
      if (reindeer.timeResting === reindeer.restTime) {
        reindeer.timeFlying = 0;
        return reindeer.timeResting = 0;
      }
    }
  };

  while (time < timeToTravel) {
    time++;
    for (i in reindeer) {
      r = reindeer[i];
      ride2(r);
    }
    maxKm = reindeer.Dancer.km;
    for (i in reindeer) {
      r = reindeer[i];
      if (r.km > maxKm) {
        maxKm = r.km;
      }
    }
    for (i in reindeer) {
      r = reindeer[i];
      if (r.km === maxKm) {
        r.points++;
      }
    }
  }

  for (i in reindeer) {
    r = reindeer[i];
    console.log(i, "has", r.points, "points and traveled", r.km, "km");
  }

}).call(this);
