let input = [
  { name: "pbga", weight: 66 },
  { name: "xhth", weight: 57 },
  { name: "ebii", weight: 61 },
  { name: "havc", weight: 66 },
  { name: "ktlj", weight: 57 },
  { name: "fwft", weight: 72, programs: [ "ktlj", "cntj", "xhth" ] },
  { name: "qoyq", weight: 66 },
  { name: "padx", weight: 45, programs: [ "pbga", "havc", "qoyq" ] },
  { name: "tknk", weight: 41, programs: [ "ugml", "padx", "fwft" ] },
  { name: "jptl", weight: 61 },
  { name: "ugml", weight: 68, programs: [ "gyxo", "ebii", "jptl" ] },
  { name: "gyxo", weight: 61 },
  { name: "cntj", weight: 57 },
]

input2 = [
  { name: "mypyemv", weight: 1058, programs: ["tdssotr", "pebnvks", "zaulju"] },
  { name: "snslv", weight: 48 },
  { name: "aytbgf", weight: 30 },
  { name: "mkcrsy", weight: 42 },
  { name: "shwcd", weight: 42 },
  { name: "muwcoy", weight: 63 },
  { name: "dabfreg", weight: 49 },
  { name: "iblvv", weight: 68 },
  { name: "qqircn", weight: 401 },
  { name: "pwpnfx", weight: 67 },
  { name: "tlnztuz", weight: 60 },
  { name: "ctglahh", weight: 17 },
  { name: "pjkgn", weight: 170, programs: ["pstttg", "xdkoxrg", "cvuvxi"] },
  { name: "ulasjv", weight: 114, programs: ["tkeney", "zaffbku"] },
  { name: "ojoim", weight: 139, programs: ["obebr", "zxwlsj"] },
  { name: "vhxxnj", weight: 109, programs: ["ooaouu", "vraxbmd"] },
  { name: "blbjzdr", weight: 40 },
  { name: "iuctosc", weight: 12, programs: ["bqmayvq", "yjzvbcb", "takuy", "qlsfhyp"] },
  { name: "mfafdfn", weight: 73 },
  { name: "egfrye", weight: 72, programs: ["uwxizpk", "igbamrm"] },
  { name: "cqokt", weight: 1487, programs: ["sjmfsib", "ubspq", "wsaugv"] },
  { name: "ekorcyg", weight: 67 },
  { name: "sfyxd", weight: 83 },
  { name: "trkiub", weight: 65 },
  { name: "muvvc", weight: 92 },
  { name: "wfhzyz", weight: 224, programs: ["swtggik", "nczykbr"] },
  { name: "acvqze", weight: 46, programs: ["itnagm", "iehtjmy"] },
  { name: "atzmoh", weight: 85 },
  { name: "euqymh", weight: 108, programs: ["wswanrt", "lvwdcah", "akpna", "siwgip"] },
  { name: "ijxbxya", weight: 323 },
  { name: "izaggi", weight: 44 },
  { name: "xokweon", weight: 14 },
  { name: "kpiqwq", weight: 158, programs: ["agvmnh", "tfgkfd"] },
  { name: "lomas", weight: 52 },
  { name: "hmktr", weight: 42 },
  { name: "xemdot", weight: 63, programs: ["xfbrfa", "erorjt", "opbpuun"] },
  { name: "xjljqp", weight: 15 },
  { name: "ruknk", weight: 35 },
  { name: "eupceiw", weight: 49 },
  { name: "hhdggir", weight: 21 },
  { name: "qzmgft", weight: 64 },
  { name: "xidme", weight: 10 },
  { name: "rwcrct", weight: 56, programs: ["muwcoy", "srpls"] },
  { name: "swtggik", weight: 62 },
  { name: "iehtjmy", weight: 99 },
  { name: "glsiv", weight: 21 },
  { name: "cdgfh", weight: 97 },
  { name: "nvuinv", weight: 82 },
  { name: "yrnvih", weight: 51, programs: ["looatgs", "sscwxvb", "wpktell"] },
  { name: "jrwyr", weight: 62 },
  { name: "lfabu", weight: 50 },
  { name: "rzmad", weight: 5 },
  { name: "fulkuc", weight: 136, programs: ["ltyun", "vqzrfnp"] },
  { name: "wlhee", weight: 8 },
  { name: "szrhxg", weight: 58 },
  { name: "stiwccj", weight: 44 },
  { name: "kutxm", weight: 25 },
  { name: "jglsot", weight: 19 },
  { name: "zxicur", weight: 34, programs: ["tkvxw", "volvsy", "mmtjv"] },
  { name: "dcdqv", weight: 17, programs: ["xvlegev", "nsiusgl", "ypnoao", "wlwzm"] },
  { name: "scrgj", weight: 63 },
  { name: "ororw", weight: 58 },
  { name: "lixut", weight: 29 },
  { name: "cqtkp", weight: 48 },
  { name: "mdxokdp", weight: 190, programs: ["qilpxc", "ertyni"] },
  { name: "xvdaje", weight: 43 },
  { name: "ertyni", weight: 83 },
  { name: "blthoo", weight: 416, programs: ["xyoog", "ryapaif", "brepu"] },
  { name: "nhjlyw", weight: 20 },
  { name: "zezwh", weight: 40 },
  { name: "byazn", weight: 17 },
  { name: "btacot", weight: 71 },
  { name: "lccyzb", weight: 72, programs: ["wrsfojv", "bpphd", "epkiz", "hihsf"] },
  { name: "ohihh", weight: 6 },
  { name: "nafjxju", weight: 347, programs: ["hptnh", "zcyjg"] },
  { name: "tlzypd", weight: 66 },
  { name: "mkctoct", weight: 77 },
  { name: "xbaqsb", weight: 97, programs: ["tpyhuwu", "goxylms"] },
  { name: "cejttl", weight: 63 },
  { name: "eyzlc", weight: 12 },
  { name: "gmxxgje", weight: 97 },
  { name: "ydajdel", weight: 245, programs: ["ydbfv", "qoxynmi"] },
  { name: "ilpcfbv", weight: 88 },
  { name: "jbwvuqa", weight: 18 },
  { name: "wjtsdig", weight: 34 },
  { name: "fyiomy", weight: 1541, programs: ["sgejm", "oywep", "vlbiiv"] },
  { name: "amxwjmq", weight: 87 },
  { name: "rmgua", weight: 6 },
  { name: "takuy", weight: 86 },
  { name: "jklzso", weight: 27 },
  { name: "qskbkjv", weight: 78 },
  { name: "dvpfhj", weight: 92 },
  { name: "ivyfvsy", weight: 8, programs: ["fptxhow", "xepmnz", "dxlgbw", "vzako"] },
  { name: "cebrhdf", weight: 42 },
  { name: "tkkaoqc", weight: 77 },
  { name: "ovgheo", weight: 64 },
  { name: "lqpnpz", weight: 31 },
  { name: "rjdcj", weight: 82 },
  { name: "xlezv", weight: 87 },
  { name: "hniys", weight: 265, programs: ["prchlcp", "uvamrg"] },
  { name: "nqonz", weight: 210, programs: ["nikle", "hsjgdl"] },
  { name: "rrvjgum", weight: 162, programs: ["mdhmfy", "cdgfh"] },
  { name: "wwewd", weight: 60 },
  { name: "fgnkr", weight: 126, programs: ["ibmga", "unsssb"] },
  { name: "bzbmtk", weight: 51 },
  { name: "kmdjw", weight: 93 },
  { name: "rqppagm", weight: 93 },
  { name: "rsush", weight: 244 },
  { name: "uavhq", weight: 38 },
  { name: "rdawn", weight: 31 },
  { name: "ilamw", weight: 26 },
  { name: "dzbqtuv", weight: 32 },
  { name: "ohnhqg", weight: 87 },
  { name: "qyrmgm", weight: 43 },
  { name: "qdeqxky", weight: 40 },
  { name: "csawtu", weight: 36 },
  { name: "ywmuda", weight: 50591, programs: ["sswubza", "jjsvzup", "hriuldj", "nddyl", "rhlbu", "ruukc"] },
  { name: "nypczc", weight: 28 },
  { name: "bvsey", weight: 74 },
  { name: "mjzkn", weight: 84 },
  { name: "fsjyp", weight: 63 },
  { name: "qaavkjk", weight: 241, programs: ["gspvb", "jrwyr"] },
  { name: "znesvt", weight: 62 },
  { name: "bfnfh", weight: 44 },
  { name: "wtedsf", weight: 76 },
  { name: "fvfzs", weight: 78, programs: ["foicoy", "zqqwfsl"] },
  { name: "xawwkeu", weight: 42 },
  { name: "wlwlu", weight: 60 },
  { name: "xswxrrf", weight: 161, programs: ["slbstvc", "narre"] },
  { name: "vqrgyeu", weight: 690, programs: ["lzjyxw", "dtxdpox", "braccf", "ttxbgy", "vkqgyqv", "jwlto", "crdiqm"] },
  { name: "bnylq", weight: 29, programs: ["ejtrjtd", "nlxjjxw", "vszskh", "qwresy"] },
  { name: "ojcor", weight: 20 },
  { name: "vxxqlw", weight: 66 },
  { name: "qrwrsw", weight: 74 },
  { name: "qkruzdo", weight: 17 },
  { name: "hriuldj", weight: 6752, programs: ["entepy", "hcsqc", "vpwwvup"] },
  { name: "hczrs", weight: 99, programs: ["lwjzn", "vvifz", "lbqtlwu", "spgvou", "hhjylgi", "ervdb"] },
  { name: "pcgfozu", weight: 113, programs: ["zgikmp", "acincpn"] },
  { name: "cwbnz", weight: 8 },
  { name: "xvaya", weight: 8 },
  { name: "xyebfi", weight: 1088, programs: ["rsush", "wxrgtti", "thufa", "hyiurrf", "efoqm", "uplvccb"] },
  { name: "txypjh", weight: 73 },
  { name: "bsaud", weight: 38 },
  { name: "mavjmb", weight: 16 },
  { name: "igyjzmj", weight: 49, programs: ["fsjyp", "sbmrcz", "ewjxaid"] },
  { name: "blssf", weight: 73, programs: ["nypczc", "oknwj"] },
  { name: "ichbonq", weight: 293, programs: ["hwkclx", "qaoygb"] },
  { name: "senunnx", weight: 96 },
  { name: "kvmcuy", weight: 1173, programs: ["blssf", "ghnims", "hagdle", "wwiei"] },
  { name: "urqute", weight: 86, programs: ["ffojoq", "iblvv"] },
  { name: "ginxj", weight: 10 },
  { name: "adxktmm", weight: 53 },
  { name: "vmejikv", weight: 1281, programs: ["hbcnhi", "zvbxsh", "bpgqat"] },
  { name: "braccf", weight: 266 },
  { name: "mouemac", weight: 9 },
  { name: "ydbfv", weight: 31 },
  { name: "sggmn", weight: 61 },
  { name: "ndjsvna", weight: 86771, programs: ["orflty", "upcttms", "cdllr"] },
  { name: "ecnra", weight: 157, programs: ["onggzld", "hnlzfo", "ssspogy", "eyzlc"] },
  { name: "ldwvnvr", weight: 72 },
  { name: "rjihyh", weight: 96 },
  { name: "dlfly", weight: 78, programs: ["rdawn", "izuwus"] },
  { name: "xdglmq", weight: 66 },
  { name: "aysnc", weight: 142, programs: ["cebrhdf", "uwswfv"] },
  { name: "lvwdcah", weight: 13 },
  { name: "tgfwmr", weight: 44 },
  { name: "hvlha", weight: 35 },
  { name: "ptuptho", weight: 283 },
  { name: "otuscl", weight: 1217, programs: ["fulkuc", "nwtyz", "urqute", "lyaszvd"] },
  { name: "uuwxren", weight: 41 },
  { name: "fwltc", weight: 15 },
  { name: "nsdmz", weight: 200, programs: ["xidme", "jvbywje"] },
  { name: "gcndqm", weight: 35 },
  { name: "yhwjhjq", weight: 47, programs: ["vsvqb", "txypjh"] },
  { name: "dtobnc", weight: 30, programs: ["fvzkg", "bvsey"] },
  { name: "kqazfnj", weight: 45 },
  { name: "wsdxxey", weight: 191, programs: ["avntwr", "ynfhkg", "eiitagr"] },
  { name: "aygufuz", weight: 96 },
  { name: "oxbck", weight: 82 },
  { name: "bpcvuic", weight: 165, programs: ["ginxj", "jxdojc", "yqpdpc", "vsxpvjg"] },
  { name: "lsepilv", weight: 99 },
  { name: "xxfgrym", weight: 64 },
  { name: "ldatid", weight: 44 },
  { name: "znyle", weight: 367 },
  { name: "jtsfhtl", weight: 255, programs: ["cbopz", "hlgfih"] },
  { name: "yfasy", weight: 22 },
  { name: "gmrgmk", weight: 32 },
  { name: "rslnynd", weight: 89 },
  { name: "smntgp", weight: 202, programs: ["bosue", "lwpjj"] },
  { name: "exjob", weight: 13 },
  { name: "etxmacn", weight: 14 },
  { name: "mytar", weight: 209, programs: ["nbujb", "dabfreg", "bsqhq"] },
  { name: "sjmfsib", weight: 264 },
  { name: "bvtwdp", weight: 75 },
  { name: "xykxl", weight: 72, programs: ["mrkkga", "tkkaoqc"] },
  { name: "acincpn", weight: 33 },
  { name: "uhtqjnr", weight: 179, programs: ["gapar", "znill"] },
  { name: "emfcg", weight: 1116, programs: ["aqfyjhl", "gikkpk", "czdkuo", "cedhxw", "ptuptho", "hniys"] },
  { name: "foghgll", weight: 67 },
  { name: "rwmrhlm", weight: 14 },
  { name: "roecqp", weight: 1134, programs: ["bziunp", "ecnra", "bpcvuic"] },
  { name: "hurkk", weight: 12, programs: ["qslsdtg", "vwlzyq", "boszvbo"] },
  { name: "phdxan", weight: 20 },
  { name: "nikle", weight: 59 },
  { name: "zkgbmgm", weight: 77, programs: ["smbrw", "yyqbv"] },
  { name: "rvdbo", weight: 88 },
  { name: "mfeed", weight: 43 },
  { name: "dygaged", weight: 89 },
  { name: "looatgs", weight: 19 },
  { name: "uigjohl", weight: 1555, programs: ["zslpkcc", "oquxa", "kpiqwq", "fvfzs"] },
  { name: "sbotg", weight: 88 },
  { name: "kvdwl", weight: 43 },
  { name: "yskbqg", weight: 11, programs: ["vjvmzpj", "dbcczgx"] },
  { name: "oypkcb", weight: 15 },
  { name: "yjchb", weight: 58 },
  { name: "fsztlli", weight: 50 },
  { name: "xoknhd", weight: 134, programs: ["aytbgf", "sxkmsi"] },
  { name: "hyiurrf", weight: 68, programs: ["mwalo", "fjahqnz", "stiwccj", "bvzurvv"] },
  { name: "nkuur", weight: 1240, programs: ["dxbxbo", "medzho", "yfasy"] },
  { name: "idhsp", weight: 148, programs: ["npdbx", "zuziby"] },
  { name: "jwlto", weight: 182, programs: ["hmktr", "qmpdncq"] },
  { name: "eziybgr", weight: 23 },
  { name: "grnajbj", weight: 26 },
  { name: "npdbx", weight: 61 },
  { name: "lbqtlwu", weight: 213, programs: ["kbdwm", "uwfgkl", "gwgodil", "lrdeob"] },
  { name: "drndkqk", weight: 168, programs: ["xokweon", "wieeikb"] },
  { name: "uuioune", weight: 83 },
  { name: "wwiei", weight: 109, programs: ["kjitif", "ozupxsh"] },
  { name: "polsl", weight: 921, programs: ["zrcxh", "gvcmhx", "hgvmyza"] },
  { name: "rdjxdt", weight: 76 },
  { name: "nrzrezq", weight: 49 },
  { name: "eescab", weight: 62 },
  { name: "onqfuf", weight: 30, programs: ["tzgzrq", "mkctoct", "wsdxfo", "scbrb"] },
  { name: "rmlqc", weight: 91 },
  { name: "hnalr", weight: 63 },
  { name: "dycnkbi", weight: 22 },
  { name: "tzgzrq", weight: 77 },
  { name: "lyaszvd", weight: 36, programs: ["bjcuq", "kmdjw"] },
  { name: "xepmnz", weight: 80 },
  { name: "vraxbmd", weight: 84 },
  { name: "seygew", weight: 176, programs: ["phocz", "hlmune"] },
  { name: "wqcsem", weight: 16716, programs: ["mwzswq", "qmlaw", "ydajdel", "zxicur"] },
  { name: "naifggq", weight: 87 },
  { name: "yyqbv", weight: 89 },
  { name: "dbgxe", weight: 135, programs: ["imdjavh", "wmaamu"] },
  { name: "pjmhz", weight: 19, programs: ["brgavyz", "esjurlp", "lhqak"] },
  { name: "wlwzm", weight: 229, programs: ["tsmzdk", "fwvhiss", "ceudr", "uwazw", "qfiva"] },
  { name: "rgswd", weight: 64 },
  { name: "pwioc", weight: 75, programs: ["zzwgd", "vxxqlw", "xdglmq"] },
  { name: "eymgei", weight: 225, programs: ["pwtps", "shwcd"] },
  { name: "xitky", weight: 40 },
  { name: "kpyvxm", weight: 76 },
  { name: "gkjvxop", weight: 84 },
  { name: "infmrxl", weight: 56 },
  { name: "ptjajhf", weight: 50, programs: ["quozn", "zvyualm"] },
  { name: "kdqwwif", weight: 54 },
  { name: "okahbh", weight: 63 },
  { name: "spgvou", weight: 217, programs: ["mavjmb", "dvkfej", "jtnbs"] },
  { name: "jxdojc", weight: 10 },
  { name: "qhdjhrx", weight: 69 },
  { name: "ialitr", weight: 42, programs: ["akpdkoi", "mzzobb", "vpynma", "lkooh", "jfshm", "fwygrf"] },
  { name: "vcgzwm", weight: 28 },
  { name: "fwygrf", weight: 305, programs: ["ocoupnc", "omgbz"] },
  { name: "cbudcq", weight: 111, programs: ["cqamyg", "dsxnt"] },
  { name: "medzho", weight: 22 },
  { name: "nqppb", weight: 1202, programs: ["emzadp", "bvtfsnv"] },
  { name: "ejwvtdi", weight: 73 },
  { name: "rtvvtqm", weight: 386, programs: ["zbxnrw", "knbui"] },
  { name: "udebtlr", weight: 81 },
  { name: "mcosbxa", weight: 40 },
  { name: "ztale", weight: 139, programs: ["qhdjhrx", "bglby"] },
  { name: "wsdxfo", weight: 77 },
  { name: "knbui", weight: 9 },
  { name: "cwpxg", weight: 34, programs: ["wsceh", "wypqz", "qytybg"] },
  { name: "hzwmfmm", weight: 22 },
  { name: "ltyun", weight: 43 },
  { name: "ooaouu", weight: 84 },
  { name: "xhrsff", weight: 38 },
  { name: "ceudr", weight: 294, programs: ["wswfp", "otymwch"] },
  { name: "dhgwl", weight: 1826, programs: ["ydtdz", "oyfjp", "jpoikof"] },
  { name: "kcskisn", weight: 177, programs: ["gzmuxt", "ifxlnmy"] },
  { name: "dtxdpox", weight: 82, programs: ["uuijugi", "dmjrx"] },
  { name: "mrkkga", weight: 77 },
  { name: "aptjif", weight: 114, programs: ["sfsqlr", "uhldcdr"] },
  { name: "nbpzp", weight: 39 },
  { name: "tywon", weight: 68 },
  { name: "dngdv", weight: 86, programs: ["picnyuy", "rqppagm", "yzdqm"] },
  { name: "xjweui", weight: 19 },
  { name: "sfsqlr", weight: 93 },
  { name: "hpxuh", weight: 45 },
  { name: "nbujb", weight: 49 },
  { name: "afpecm", weight: 93 },
  { name: "slbstvc", weight: 74 },
  { name: "cbryc", weight: 76, programs: ["dgwpdyh", "fadosqb"] },
  { name: "jczlwrg", weight: 97, programs: ["mcvmt", "ysptuct"] },
  { name: "adyaz", weight: 58 },
  { name: "kcpxll", weight: 29, programs: ["cykkbh", "rvdbo"] },
  { name: "zbxnrw", weight: 9 },
  { name: "betps", weight: 17 },
  { name: "zdguboh", weight: 45 },
  { name: "zqqwfsl", weight: 71 },
  { name: "bvzurvv", weight: 44 },
  { name: "mvhjvsx", weight: 74 },
  { name: "yksfjd", weight: 172, programs: ["okobh", "tgfwmr", "zkjxiqd", "sksyosg"] },
  { name: "fszzls", weight: 1508, programs: ["lskwu", "ymaow", "uigjohl"] },
  { name: "fudnt", weight: 58 },
  { name: "tjlzt", weight: 51 },
  { name: "rthgd", weight: 226 },
  { name: "zqakqf", weight: 152, programs: ["axaojh", "bbojjz"] },
  { name: "jsoaf", weight: 85, programs: ["peuzd", "kervui", "lccyzb", "rtvvtqm", "pxfxcwi"] },
  { name: "kayutk", weight: 135, programs: ["cqtkp", "ertegmg", "xcmjj"] },
  { name: "eccqmq", weight: 61 },
  { name: "gxmjfay", weight: 56 },
  { name: "uhldcdr", weight: 93 },
  { name: "atgslqo", weight: 189, programs: ["ypflzv", "vxrjtk"] },
  { name: "tmqmur", weight: 51 },
  { name: "eusabu", weight: 51 },
  { name: "rrhqyi", weight: 88 },
  { name: "dlblhs", weight: 50 },
  { name: "mygap", weight: 82, programs: ["rwnwac", "jnqyz", "geaqa", "bacdnzx"] },
  { name: "iyylin", weight: 244, programs: ["nlnalmy", "tuvvzii"] },
  { name: "jsmmy", weight: 149, programs: ["rjihyh", "njftjr", "mjpctj"] },
  { name: "lgiwxh", weight: 110, programs: ["hsrzvw", "mwtpyul"] },
  { name: "pihmrxm", weight: 7418, programs: ["nqlzz", "kpvixun", "ecgci", "hzltk", "kayutk"] },
  { name: "sxmeh", weight: 1344, programs: ["eqfhg", "ptjajhf", "oglxcmb"] },
  { name: "hcsqc", weight: 88, programs: ["xbyqz", "ubwbr", "mygap", "kcgsp", "zlkpb"] },
  { name: "crayus", weight: 20 },
  { name: "zvbxsh", weight: 45, programs: ["mkaznh", "hfhdret"] },
  { name: "quehgo", weight: 76 },
  { name: "kmkfzcz", weight: 20 },
  { name: "dwlbh", weight: 89 },
  { name: "badmffy", weight: 33 },
  { name: "zilhzgj", weight: 327, programs: ["jihuf", "jdylgmm"] },
  { name: "tuvios", weight: 10, programs: ["mgtxs", "uapgx"] },
  { name: "crnkf", weight: 86 },
  { name: "jedncgk", weight: 166, programs: ["bzbmtk", "wgwmd"] },
  { name: "uxpdj", weight: 18 },
  { name: "uapgx", weight: 65 },
  { name: "kapgfn", weight: 71 },
  { name: "viytym", weight: 1583, programs: ["jcswni", "hdhay", "drndkqk"] },
  { name: "vjabq", weight: 163 },
  { name: "ywigueo", weight: 31 },
  { name: "ypnoao", weight: 2033, programs: ["zpyjk", "sfyxd"] },
  { name: "yanhp", weight: 28 },
  { name: "xdkoxrg", weight: 36 },
  { name: "onggzld", weight: 12 },
  { name: "tzdhk", weight: 2466, programs: ["mfeed", "ftjqj"] },
  { name: "wbmho", weight: 596, programs: ["htfkm", "xatcr", "sotsaq", "xemdot", "jdphz"] },
  { name: "fzorad", weight: 72 },
  { name: "dalfsy", weight: 81 },
  { name: "pidgo", weight: 1422, programs: ["gxqhw", "wrpla", "lncrnjm"] },
  { name: "teivbkx", weight: 88 },
  { name: "wwmczwe", weight: 38 },
  { name: "iqxuy", weight: 186, programs: ["grxsygp", "zariy"] },
  { name: "zxwlsj", weight: 49 },
  { name: "kjmlecw", weight: 13 },
  { name: "vevsn", weight: 21 },
  { name: "cvuvxi", weight: 36 },
  { name: "akpna", weight: 13 },
  { name: "censvvb", weight: 47, programs: ["hekhmmx", "fhbsh", "zilhzgj", "qaavkjk", "ykfuiik", "dngdv"] },
  { name: "ulwogj", weight: 52 },
  { name: "xiplruw", weight: 67 },
  { name: "sddzrpe", weight: 20 },
  { name: "uwswfv", weight: 42 },
  { name: "ofgni", weight: 68 },
  { name: "duilk", weight: 154, programs: ["icyem", "qmiwmcd"] },
  { name: "uoineor", weight: 8 },
  { name: "grhiyhw", weight: 138, programs: ["lixut", "ieexpjt", "vsqpyrc"] },
  { name: "hztml", weight: 155, programs: ["rwizsex", "fwxzdr", "zpgad"] },
  { name: "wpktell", weight: 19 },
  { name: "nsiusgl", weight: 36, programs: ["hmeqffk", "yvnguxg", "jrwro", "uhtqjnr", "xswxrrf", "atgslqo", "eymgei"] },
  { name: "niuavpj", weight: 80 },
  { name: "bmuxik", weight: 1638, programs: ["vtxojlh", "betps", "byazn"] },
  { name: "zmvaqzk", weight: 56 },
  { name: "ygvihck", weight: 1847, programs: ["hurkk", "yrnvih", "qhvtakl"] },
  { name: "vpynma", weight: 81, programs: ["rjdcj", "nvuinv", "bbyfznm", "oxbck"] },
  { name: "hmeqffk", weight: 77, programs: ["letlj", "ihtqyi", "szrhxg", "ggdgz"] },
  { name: "yqpdpc", weight: 10 },
  { name: "zvyualm", weight: 33 },
  { name: "ebmlo", weight: 14 },
  { name: "qquhmw", weight: 8 },
  { name: "eiajcj", weight: 50 },
  { name: "zrcxh", weight: 61, programs: ["nrzrezq", "hfauih", "eupceiw", "dsfrgq"] },
  { name: "bfbjr", weight: 2512, programs: ["sddzrpe", "kmkfzcz"] },
  { name: "yrmfqoy", weight: 78 },
  { name: "iaxol", weight: 89, programs: ["dywxgkl", "badmffy"] },
  { name: "qmlaw", weight: 191, programs: ["vxagjlw", "bzziw"] },
  { name: "luedvgo", weight: 51 },
  { name: "qnyjwud", weight: 18 },
  { name: "gzwdr", weight: 198, programs: ["bqsjvdf", "iqyhxcw"] },
  { name: "ghnims", weight: 72, programs: ["blkpn", "jglsot", "kwxszx"] },
  { name: "sczhwf", weight: 6688, programs: ["tlbdrz", "emfcg", "mtlrg", "bjnxl"] },
  { name: "jmtvijt", weight: 52 },
  { name: "qscxur", weight: 97 },
  { name: "qfiva", weight: 210, programs: ["dvpfhj", "nwtgwj"] },
  { name: "orflty", weight: 82, programs: ["xnfff", "rgoiojv", "hnovowe", "qsidq", "ncrxh"] },
  { name: "liopy", weight: 51 },
  { name: "dztfd", weight: 14 },
  { name: "kiyra", weight: 1333, programs: ["xykxl", "smntgp", "vopguxl", "ihrwjcv"] },
  { name: "oogodf", weight: 487, programs: ["jtsfhtl", "pwioc", "jtbnzi"] },
  { name: "rhsppv", weight: 110, programs: ["apitzsg", "cxewh"] },
  { name: "rhtin", weight: 91 },
  { name: "dkjgzys", weight: 124, programs: ["fuzpme", "qjhiy"] },
  { name: "tyuftbm", weight: 196, programs: ["vvdnnin", "tlzypd"] },
  { name: "jnqyz", weight: 71 },
  { name: "wmiupn", weight: 30 },
  { name: "vioxf", weight: 58 },
  { name: "cslvss", weight: 10, programs: ["teivbkx", "ozqmk"] },
  { name: "wswfp", weight: 50 },
  { name: "nwosqhj", weight: 720, programs: ["zmbunn", "zkkvo", "rhoexv", "ojoim"] },
  { name: "wwudvj", weight: 58 },
  { name: "tovzpw", weight: 41 },
  { name: "sksyosg", weight: 44 },
  { name: "brepu", weight: 7 },
  { name: "ykkcei", weight: 19, programs: ["espnx", "wqcsem", "sgknjo", "sczhwf", "dbkkk", "obxht", "etyuvh"] },
  { name: "izuwus", weight: 31 },
  { name: "xxtwrvp", weight: 63 },
  { name: "aqfyjhl", weight: 111, programs: ["bvxlrk", "dlamw"] },
  { name: "tysys", weight: 9 },
  { name: "mmjvskv", weight: 14 },
  { name: "yugpzh", weight: 108, programs: ["kvdwl", "xvdaje"] },
  { name: "ejtrjtd", weight: 93 },
  { name: "ibmga", weight: 50 },
  { name: "etxziey", weight: 228, programs: ["xvaya", "qquhmw"] },
  { name: "azyzcr", weight: 72749, programs: ["hciyw", "pihmrxm", "ywgvt", "dcdqv", "dieqdax", "fszzls"] },
  { name: "dbcczgx", weight: 84 },
  { name: "vdaipmp", weight: 39 },
  { name: "erxsplp", weight: 49 },
  { name: "hagdle", weight: 13, programs: ["fagghhk", "gisbvap"] },
  { name: "esqjbr", weight: 76 },
  { name: "kcgsp", weight: 350, programs: ["ckflx", "wlhee"] },
  { name: "ownte", weight: 89 },
  { name: "dbxwe", weight: 1571, programs: ["cwpxg", "nmqbvpq", "dtobnc"] },
  { name: "mlqhbm", weight: 87 },
  { name: "prchlcp", weight: 9 },
  { name: "omgbz", weight: 52 },
  { name: "msshu", weight: 93 },
  { name: "fmltl", weight: 73 },
  { name: "jdphz", weight: 195, programs: ["wwewd", "jyljgi"] },
  { name: "hzltk", weight: 191, programs: ["dycnkbi", "hzwmfmm", "ynfor", "bflcu"] },
  { name: "owyvbh", weight: 36 },
  { name: "ihtqyi", weight: 58 },
  { name: "zmbunn", weight: 59, programs: ["dygaged", "yzgavqk"] },
  { name: "goxylms", weight: 54 },
  { name: "eknhj", weight: 24 },
  { name: "etyuvh", weight: 16720, programs: ["atwydaw", "ulasjv", "qvgqro", "hfwvb"] },
  { name: "ookiv", weight: 67 },
  { name: "krrqud", weight: 257 },
  { name: "bziunp", weight: 69, programs: ["ofgni", "tywon"] },
  { name: "tquiwoi", weight: 53 },
  { name: "zyfceqn", weight: 96 },
  { name: "sxkmsi", weight: 30 },
  { name: "nefuqmx", weight: 36 },
  { name: "stzod", weight: 62 },
  { name: "letlj", weight: 58 },
  { name: "aledvka", weight: 348 },
  { name: "bqqmp", weight: 58, programs: ["zqakqf", "ulnegp", "cjxht", "tclpy"] },
  { name: "jbttm", weight: 58, programs: ["stzod", "eescab"] },
  { name: "ojspxc", weight: 92 },
  { name: "bdjhzp", weight: 28, programs: ["bdxixic", "zyfceqn", "pzjttn", "psfvjcp"] },
  { name: "ypflzv", weight: 60 },
  { name: "qscii", weight: 51 },
  { name: "gdise", weight: 7 },
  { name: "uflkv", weight: 172, programs: ["scfmycd", "tdocp"] },
  { name: "mvllqsx", weight: 55 },
  { name: "yvnguxg", weight: 309 },
  { name: "mwtpyul", weight: 47 },
  { name: "uzuqqja", weight: 28, programs: ["jhouok", "zmvaqzk"] },
  { name: "htfkm", weight: 303, programs: ["ordnoxv", "ohihh"] },
  { name: "hdefj", weight: 60, programs: ["kfofavd", "sfnmpjd"] },
  { name: "kfnpyl", weight: 25 },
  { name: "epkiz", weight: 83 },
  { name: "xnasc", weight: 99 },
  { name: "enlerk", weight: 82 },
  { name: "bdfgsx", weight: 385, programs: ["yhohp", "vcgzwm"] },
  { name: "bcslfkc", weight: 208 },
  { name: "mlxtf", weight: 267, programs: ["qnzrznc", "lfabu"] },
  { name: "zpyjk", weight: 83 },
  { name: "vjvmzpj", weight: 84 },
  { name: "cxewh", weight: 36 },
  { name: "huozxzo", weight: 89 },
  { name: "fkstubd", weight: 99 },
  { name: "rkddlwk", weight: 1718, programs: ["pjkgn", "wilmnmv", "duilk"] },
  { name: "uwazw", weight: 224, programs: ["atzmoh", "fpart"] },
  { name: "hbhvg", weight: 32 },
  { name: "ruukc", weight: 26, programs: ["cidcth", "eqoivx", "ccdvhvz", "ialitr", "dkszj"] },
  { name: "siwgip", weight: 13 },
  { name: "igxruya", weight: 186, programs: ["lymfmlp", "ouxhs"] },
  { name: "lzsao", weight: 39 },
  { name: "dlamw", weight: 86 },
  { name: "cdutkux", weight: 215, programs: ["vevsn", "gofcp"] },
  { name: "wvzeiwz", weight: 141, programs: ["dppnlm", "jedncgk", "didaob", "guzxauy", "ltzsoxk", "dkjgzys"] },
  { name: "qmpdncq", weight: 42 },
  { name: "fnsflkm", weight: 77 },
  { name: "drnxkqu", weight: 61 },
  { name: "bzziw", weight: 58 },
  { name: "wyciek", weight: 45, programs: ["iyaxfqg", "lythu"] },
  { name: "aanhl", weight: 6 },
  { name: "imobzk", weight: 192, programs: ["uoineor", "zhlbg"] },
  { name: "jkhfw", weight: 85 },
  { name: "jlosq", weight: 84 },
  { name: "htfhn", weight: 1523, programs: ["xoknhd", "yugpzh", "bniphb"] },
  { name: "bgute", weight: 51 },
  { name: "zzitpl", weight: 77, programs: ["zddflk", "uxbkndn"] },
  { name: "hsrzvw", weight: 47 },
  { name: "dmjrx", weight: 92 },
  { name: "tfwfd", weight: 41 },
  { name: "smbrw", weight: 89 },
  { name: "uxcmt", weight: 199, programs: ["lgwgc", "ebximw"] },
  { name: "xbyqz", weight: 268, programs: ["fntqeb", "etmlid"] },
  { name: "kjitif", weight: 10 },
  { name: "oknwj", weight: 28 },
  { name: "brgavyz", weight: 48 },
  { name: "fhbsh", weight: 197, programs: ["jlosq", "ckzmd"] },
  { name: "pdhmgx", weight: 18 },
  { name: "yjzvbcb", weight: 86 },
  { name: "qwresy", weight: 93 },
  { name: "ucuhiy", weight: 81 },
  { name: "uyzts", weight: 40 },
  { name: "erorjt", weight: 84 },
  { name: "hhjylgi", weight: 73, programs: ["senunnx", "aygufuz"] },
  { name: "nthwie", weight: 98, programs: ["cblwb", "drnxkqu"] },
  { name: "wrsfojv", weight: 83 },
  { name: "ppkmfx", weight: 1457, programs: ["bzqoi", "hdiqnt", "igyjzmj"] },
  { name: "uwfgkl", weight: 13 },
  { name: "vzpakr", weight: 35 },
  { name: "nxyku", weight: 41 },
  { name: "nwtyz", weight: 152, programs: ["zigvdka", "gcndqm"] },
  { name: "tmrukz", weight: 82 },
  { name: "mkaus", weight: 82 },
  { name: "ebximw", weight: 62 },
  { name: "kmbky", weight: 263, programs: ["rgswd", "xxfgrym"] },
  { name: "ckzmd", weight: 84 },
  { name: "ulnegp", weight: 196, programs: ["azgcixi", "hibvd"] },
  { name: "cbato", weight: 81 },
  { name: "fhhim", weight: 63 },
  { name: "ybayf", weight: 35 },
  { name: "bvfrrlk", weight: 6 },
  { name: "mluvdn", weight: 49, programs: ["ilpcfbv", "sbotg"] },
  { name: "jvamv", weight: 20 },
  { name: "lzqmapb", weight: 65 },
  { name: "cedhxw", weight: 273, programs: ["owxjs", "rzmad"] },
  { name: "icyem", weight: 62 },
  { name: "mwfweu", weight: 7 },
  { name: "vlbiiv", weight: 28, programs: ["uyzts", "xitky", "jzxslw", "mcosbxa"] },
  { name: "cfynk", weight: 60 },
  { name: "vwlzyq", weight: 32 },
  { name: "vsxpvjg", weight: 10 },
  { name: "pmiwg", weight: 7 },
  { name: "gcbwu", weight: 401 },
  { name: "ippiayw", weight: 40 },
  { name: "oywep", weight: 84, programs: ["jmtvijt", "lomas"] },
  { name: "gbbqu", weight: 60, programs: ["igxruya", "zhjrvb", "mytar", "vkgmm", "rrvjgum", "mdxokdp", "iuctosc"] },
  { name: "upvqdc", weight: 35 },
  { name: "tkvxw", weight: 91 },
  { name: "yofaj", weight: 17 },
  { name: "mcvmt", weight: 65 },
  { name: "lythu", weight: 80 },
  { name: "spcxr", weight: 103, programs: ["tfwfd", "frmkl", "nxyku"] },
  { name: "ocoupnc", weight: 52 },
  { name: "yirlhg", weight: 347, programs: ["jklzso", "pbrakxw"] },
  { name: "dieqdax", weight: 3809, programs: ["xsmnbd", "nwosqhj", "cbsqsb"] },
  { name: "jppbqj", weight: 39 },
  { name: "wtbkj", weight: 1625, programs: ["xeaftl", "euqymh", "qaybrra"] },
  { name: "czpmzex", weight: 61 },
  { name: "hdiqnt", weight: 182, programs: ["xvmmt", "yanhp"] },
  { name: "uqmxlbi", weight: 87, programs: ["sgevc", "payocx", "bkapyf", "btkish"] },
  { name: "dxlgbw", weight: 80 },
  { name: "cbsqsb", weight: 86, programs: ["xvapp", "rthgd", "spcxr", "fgnkr", "vquis", "dutblrl", "aysnc"] },
  { name: "otymwch", weight: 50 },
  { name: "yfxiz", weight: 52 },
  { name: "zkvyo", weight: 246 },
  { name: "rhoexv", weight: 95, programs: ["gmslbkd", "kapgfn"] },
  { name: "ynfhkg", weight: 49 },
  { name: "nkallms", weight: 92 },
  { name: "tdssotr", weight: 81, programs: ["scrgj", "okahbh"] },
  { name: "vpwwvup", weight: 1168, programs: ["rexdsi", "hpkqdn", "pqvvi"] },
  { name: "jzxslw", weight: 40 },
  { name: "xvmmt", weight: 28 },
  { name: "vwubn", weight: 80 },
  { name: "dywxgkl", weight: 33 },
  { name: "lkooh", weight: 223, programs: ["igrfqy", "znesvt", "qaddd"] },
  { name: "obebr", weight: 49 },
  { name: "owlxwub", weight: 39 },
  { name: "ubspq", weight: 94, programs: ["coxuj", "oiiufpg"] },
  { name: "hmqyh", weight: 255 },
  { name: "jztwlhz", weight: 111, programs: ["xfzbans", "brlrqy", "zdguboh"] },
  { name: "vcguzz", weight: 94, programs: ["fjvazs", "blthoo", "jsmmy", "ichbonq", "ujrnrd"] },
  { name: "jdylgmm", weight: 19 },
  { name: "snoxm", weight: 42 },
  { name: "kaqrd", weight: 80, programs: ["ifuvb", "nneqad"] },
  { name: "ihrwjcv", weight: 146, programs: ["zezwh", "ippiayw"] },
  { name: "mkaznh", weight: 46 },
  { name: "bqsjvdf", weight: 40 },
  { name: "zhjrvb", weight: 214, programs: ["btacot", "ajgkut"] },
  { name: "ifxlnmy", weight: 95 },
  { name: "geaqa", weight: 71 },
  { name: "sochjt", weight: 833, programs: ["pcgfozu", "yskbqg", "ooqtpgb"] },
  { name: "uuqzc", weight: 64 },
  { name: "narre", weight: 74 },
  { name: "dgwpdyh", weight: 99 },
  { name: "jjzna", weight: 1427, programs: ["obpbif", "wzvubdc", "idhsp"] },
  { name: "qobvna", weight: 21 },
  { name: "ggdgz", weight: 58 },
  { name: "boszvbo", weight: 32 },
  { name: "cqxfcqr", weight: 47, programs: ["owyvbh", "nefuqmx", "fmlqbe"] },
  { name: "eaayvc", weight: 26 },
  { name: "ervdb", weight: 202, programs: ["hhdggir", "qobvna", "glsiv"] },
  { name: "vsvqb", weight: 73 },
  { name: "cfrcn", weight: 14 },
  { name: "bosue", weight: 12 },
  { name: "agvmnh", weight: 31 },
  { name: "bjcuq", weight: 93 },
  { name: "rgziu", weight: 47, programs: ["bdfgsx", "muewwty", "hhyqt"] },
  { name: "bdxixic", weight: 96 },
  { name: "hmslvhd", weight: 64 },
  { name: "cqamyg", weight: 83 },
  { name: "ypvcfg", weight: 83, programs: ["aledvka", "bazgple", "gazra", "wfhzyz", "yksfjd", "uflkv"] },
  { name: "wsceh", weight: 48 },
  { name: "apitzsg", weight: 36 },
  { name: "rgsktf", weight: 152, programs: ["ibigmtm", "nggqv"] },
  { name: "psfvjcp", weight: 96 },
  { name: "hfauih", weight: 49 },
  { name: "bazgple", weight: 80, programs: ["ookiv", "ekorcyg", "xiplruw", "zygeve"] },
  { name: "fecfcyc", weight: 81 },
  { name: "klpjlll", weight: 7 },
  { name: "tsmzdk", weight: 394 },
  { name: "jjsvzup", weight: 7439, programs: ["bmuxik", "hczrs", "kvmcuy"] },
  { name: "tfsenz", weight: 52, programs: ["whpgoe", "kpyvxm"] },
  { name: "vzako", weight: 80 },
  { name: "rdmyua", weight: 373, programs: ["ovlle", "mwfweu", "kxsio", "zfvnm"] },
  { name: "yzdqm", weight: 93 },
  { name: "nawecgw", weight: 30, programs: ["zvatf", "sixatzk", "bgwym", "ztale", "cbudcq", "vhxxnj"] },
  { name: "hlgfih", weight: 9 },
  { name: "lgwgc", weight: 62 },
  { name: "qaoygb", weight: 72 },
  { name: "zcnkvpn", weight: 88 },
  { name: "sgejm", weight: 162, programs: ["ywjdepk", "xsbbpem"] },
  { name: "lmpji", weight: 117, programs: ["uavhq", "wwmczwe"] },
  { name: "uuijugi", weight: 92 },
  { name: "zpgad", weight: 41 },
  { name: "ndxlz", weight: 39 },
  { name: "tclpy", weight: 78, programs: ["shnov", "qskbkjv", "awscps"] },
  { name: "kxsio", weight: 7 },
  { name: "oglxcmb", weight: 116 },
  { name: "awscps", weight: 78 },
  { name: "ajgkut", weight: 71 },
  { name: "gapar", weight: 65 },
  { name: "zsezyi", weight: 48, programs: ["pwpnfx", "foghgll"] },
  { name: "lakdjt", weight: 18 },
  { name: "vquis", weight: 130, programs: ["cofbsq", "snslv"] },
  { name: "demwz", weight: 90 },
  { name: "zefog", weight: 15 },
  { name: "akpdkoi", weight: 385, programs: ["trycav", "lmeql", "puhlt"] },
  { name: "xcxuhpd", weight: 665, programs: ["onqfuf", "tbhokxb", "wsdxxey"] },
  { name: "lampfo", weight: 26 },
  { name: "qlsfhyp", weight: 86 },
  { name: "ijpak", weight: 93 },
  { name: "cmwxozx", weight: 75 },
  { name: "mzzobb", weight: 369, programs: ["phdxan", "nhjlyw"] },
  { name: "vkgmm", weight: 328, programs: ["cfrcn", "mmjvskv"] },
  { name: "ckflx", weight: 8 },
  { name: "czgpah", weight: 18 },
  { name: "dsfrgq", weight: 49 },
  { name: "pzjttn", weight: 96 },
  { name: "mwalo", weight: 44 },
  { name: "dajhp", weight: 90 },
  { name: "vdjyb", weight: 73 },
  { name: "shnov", weight: 78 },
  { name: "sythobq", weight: 263, programs: ["fpgjkf", "ulwogj"] },
  { name: "yzgavqk", weight: 89 },
  { name: "eqfhg", weight: 14, programs: ["vxlasq", "wjtsdig", "xerwajl"] },
  { name: "bvtfsnv", weight: 84 },
  { name: "trycav", weight: 8 },
  { name: "xjlyt", weight: 54 },
  { name: "xmkxjgq", weight: 53 },
  { name: "cvenf", weight: 12 },
  { name: "mgxgsx", weight: 74, programs: ["jjtsj", "anykkx"] },
  { name: "gwwrlp", weight: 92 },
  { name: "ieexpjt", weight: 29 },
  { name: "gowhuw", weight: 86 },
  { name: "bbojjz", weight: 80 },
  { name: "vkqgyqv", weight: 162, programs: ["bdgcym", "yfxiz"] },
  { name: "fzpjtgv", weight: 243, programs: ["klpjlll", "pmiwg"] },
  { name: "dzjhdt", weight: 140, programs: ["sudoea", "rwmrhlm", "etxmacn"] },
  { name: "ammhz", weight: 85 },
  { name: "ibigmtm", weight: 61 },
  { name: "bpgqat", weight: 21, programs: ["yjchb", "kcyuui"] },
  { name: "xerwajl", weight: 34 },
  { name: "pyentj", weight: 85 },
  { name: "dbkkk", weight: 3209, programs: ["otuscl", "dhgwl", "fyiomy", "wtbkj", "dbxwe", "jsoaf", "htfhn"] },
  { name: "rexdsi", weight: 64, programs: ["ijpak", "msshu"] },
  { name: "bsqhq", weight: 49 },
  { name: "picnyuy", weight: 93 },
  { name: "okobh", weight: 44 },
  { name: "zcyjg", weight: 22 },
  { name: "upcttms", weight: 4492, programs: ["polsl", "sgamtw", "sxmeh", "vmejikv", "nawecgw"] },
  { name: "efomsfh", weight: 35 },
  { name: "pstttg", weight: 36 },
  { name: "lymfmlp", weight: 85 },
  { name: "jknlaad", weight: 141, programs: ["yvovprt", "qposz"] },
  { name: "idngwil", weight: 53 },
  { name: "qpism", weight: 1332, programs: ["kutcu", "etxziey", "acvqze", "xkari", "mgxgsx"] },
  { name: "xxohf", weight: 36 },
  { name: "rxocfu", weight: 31 },
  { name: "qjhiy", weight: 72 },
  { name: "mtlrg", weight: 1379, programs: ["kcpxll", "dbgxe", "vpiug", "xbaqsb", "wnqqem", "wyciek", "vzfmojd"] },
  { name: "rhlbu", weight: 11221, programs: ["xnmoq", "fzpjtgv", "lftjq", "cdutkux", "krrqud"] },
  { name: "zsdog", weight: 148, programs: ["xxtwrvp", "hnalr"] },
  { name: "xnmoq", weight: 113, programs: ["fzorad", "ldwvnvr"] },
  { name: "rwizsex", weight: 41 },
  { name: "hfhdret", weight: 46 },
  { name: "xvlegev", weight: 477, programs: ["kaqrd", "egfrye", "fmxhbs", "jztwlhz", "zkvyo", "nofuzdd", "lhjmsy"] },
  { name: "qaddd", weight: 62 },
  { name: "fjvazs", weight: 93, programs: ["grrfq", "hlfmjm", "crnkf", "gowhuw"] },
  { name: "fswhx", weight: 23 },
  { name: "qoxynmi", weight: 31 },
  { name: "duwat", weight: 39, programs: ["libqry", "tyuftbm", "ivyfvsy", "nqonz", "xuqosu"] },
  { name: "bniphb", weight: 42, programs: ["awcvbgl", "quehgo"] },
  { name: "emzadp", weight: 84 },
  { name: "bqdtj", weight: 84 },
  { name: "obxqu", weight: 185, programs: ["cwqzpce", "dztfd", "ebmlo"] },
  { name: "atuotwh", weight: 30 },
  { name: "lhqak", weight: 48 },
  { name: "sotsaq", weight: 315 },
  { name: "qmiwmcd", weight: 62 },
  { name: "ikjorey", weight: 94, programs: ["ojspxc", "uktjzbb"] },
  { name: "wzvubdc", weight: 92, programs: ["rslnynd", "dwlbh"] },
  { name: "oiiufpg", weight: 85 },
  { name: "pebnvks", weight: 123, programs: ["hjfuq", "snoxm"] },
  { name: "nggqv", weight: 61 },
  { name: "bqmayvq", weight: 86 },
  { name: "xvarjo", weight: 51 },
  { name: "rvqwfsn", weight: 84, programs: ["rxowzf", "xvarjo"] },
  { name: "rgoiojv", weight: 5, programs: ["czxjike", "mlxtf", "uqmxlbi", "sythobq", "jnmrl", "kcskisn", "znyle"] },
  { name: "efomf", weight: 87 },
  { name: "ynfor", weight: 22 },
  { name: "hihsf", weight: 83 },
  { name: "bkapyf", weight: 70 },
  { name: "gikkpk", weight: 40, programs: ["hyohkqq", "ktfzzi", "dalfsy"] },
  { name: "fvaow", weight: 54 },
  { name: "ilcvskn", weight: 201, programs: ["jmjxm", "cvenf"] },
  { name: "zddflk", weight: 74 },
  { name: "wmaamu", weight: 35 },
  { name: "smkqkas", weight: 39 },
  { name: "cbopz", weight: 9 },
  { name: "vszskh", weight: 93 },
  { name: "gpkrbvt", weight: 91 },
  { name: "yodja", weight: 82 },
  { name: "bvcujod", weight: 85 },
  { name: "bdjhrqu", weight: 199, programs: ["kjmlecw", "exjob"] },
  { name: "uwxizpk", weight: 87 },
  { name: "hnlzfo", weight: 12 },
  { name: "qilpxc", weight: 83 },
  { name: "pryxkzp", weight: 57, programs: ["zmaqz", "gvangx"] },
  { name: "mjpctj", weight: 96 },
  { name: "fadosqb", weight: 99 },
  { name: "xuqosu", weight: 298, programs: ["fwltc", "cqvwrm"] },
  { name: "lbmkk", weight: 79, programs: ["eusabu", "dchdrpf", "liopy"] },
  { name: "zhyhc", weight: 41 },
  { name: "xkari", weight: 70, programs: ["efomf", "ohnhqg"] },
  { name: "lcblh", weight: 674, programs: ["nhzxvd", "lbmkk", "iqxuy"] },
  { name: "ouxhs", weight: 85 },
  { name: "bvxlrk", weight: 86 },
  { name: "etmlid", weight: 49 },
  { name: "rujeuns", weight: 23 },
  { name: "mgtxs", weight: 65 },
  { name: "tvxhhko", weight: 69, programs: ["xgdqc", "afpecm"] },
  { name: "bflcu", weight: 22 },
  { name: "fmlqbe", weight: 36 },
  { name: "qnzrznc", weight: 50 },
  { name: "dwogs", weight: 48 },
  { name: "tlbdrz", weight: 7, programs: ["gcbwu", "lgatvlk", "diflt", "bnylq", "yirlhg", "rdmyua", "qqircn"] },
  { name: "ezpwfm", weight: 50 },
  { name: "yunufd", weight: 51 },
  { name: "ecgci", weight: 107, programs: ["pdgdceb", "qyrmgm", "nzxlkrf", "bjcgvr"] },
  { name: "tkeney", weight: 96 },
  { name: "pdgdceb", weight: 43 },
  { name: "puhlt", weight: 8 },
  { name: "gzfqvb", weight: 78 },
  { name: "jyljgi", weight: 60 },
  { name: "czqieu", weight: 81 },
  { name: "pjmolr", weight: 376, programs: ["czgpah", "pdhmgx"] },
  { name: "nhzxvd", weight: 104, programs: ["qzmgft", "uuqzc"] },
  { name: "gjfmnpu", weight: 25 },
  { name: "ykfuiik", weight: 205, programs: ["ycmcpqd", "qdeqxky", "emsuiot", "miimy"] },
  { name: "brlrqy", weight: 45 },
  { name: "vvifz", weight: 169, programs: ["lkvdgsk", "nqrgm", "pohuglk"] },
  { name: "cweuc", weight: 37 },
  { name: "vxlasq", weight: 34 },
  { name: "cblwb", weight: 61 },
  { name: "cykkbh", weight: 88 },
  { name: "esjurlp", weight: 48 },
  { name: "vjzteyv", weight: 33 },
  { name: "kpvixun", weight: 35, programs: ["eccqmq", "eeqon", "zdgotwb", "sggmn"] },
  { name: "bacdnzx", weight: 71 },
  { name: "tuvvzii", weight: 17 },
  { name: "plnuv", weight: 81 },
  { name: "tmrvz", weight: 37 },
  { name: "peuzd", weight: 236, programs: ["nlyrnm", "kjdboj"] },
  { name: "tpyhuwu", weight: 54 },
  { name: "wwunqd", weight: 85 },
  { name: "ttxbgy", weight: 254, programs: ["bvfrrlk", "xomgh"] },
  { name: "vjsezr", weight: 173, programs: ["upvqdc", "ruknk", "vzpakr"] },
  { name: "ftjqj", weight: 43 },
  { name: "ysptuct", weight: 65 },
  { name: "czdkuo", weight: 283 },
  { name: "sgevc", weight: 70 },
  { name: "zslpkcc", weight: 220 },
  { name: "fptxhow", weight: 80 },
  { name: "oltfpgi", weight: 53 },
  { name: "sscwxvb", weight: 19 },
  { name: "cmupq", weight: 20 },
  { name: "yfblca", weight: 26 },
  { name: "thufa", weight: 124, programs: ["arzanp", "tlnztuz"] },
  { name: "gzmuxt", weight: 95 },
  { name: "bpphd", weight: 83 },
  { name: "vzfmojd", weight: 39, programs: ["xqsynow", "uuioune"] },
  { name: "cbsbti", weight: 303, programs: ["izaggi", "nwgqq"] },
  { name: "lrdeob", weight: 13 },
  { name: "libqry", weight: 182, programs: ["vdjyb", "ejwvtdi"] },
  { name: "whpgoe", weight: 76 },
  { name: "yfnxyuz", weight: 99 },
  { name: "foicoy", weight: 71 },
  { name: "lkvdgsk", weight: 32 },
  { name: "zhlbg", weight: 8 },
  { name: "kgxpfbq", weight: 42 },
  { name: "nlnalmy", weight: 17 },
  { name: "nlxjjxw", weight: 93 },
  { name: "lncrnjm", weight: 21, programs: ["ldatid", "bfnfh"] },
  { name: "hapofa", weight: 18 },
  { name: "owxjs", weight: 5 },
  { name: "kcyuui", weight: 58 },
  { name: "jnmrl", weight: 325, programs: ["vaswfpp", "tpurix"] },
  { name: "zmaqz", weight: 49 },
  { name: "mehhq", weight: 95, programs: ["wtedsf", "esqjbr", "gbqklts"] },
  { name: "mwzswq", weight: 161, programs: ["mfafdfn", "fmltl"] },
  { name: "eeqon", weight: 61 },
  { name: "fmxhbs", weight: 144, programs: ["tjlzt", "tmqmur"] },
  { name: "blkpn", weight: 19 },
  { name: "gspvb", weight: 62 },
  { name: "obxht", weight: 4918, programs: ["viytym", "exqzjfk", "wbmho", "ppkmfx", "ypvcfg", "ygvihck"] },
  { name: "bjbxg", weight: 115, programs: ["gxmjfay", "infmrxl"] },
  { name: "grxsygp", weight: 23 },
  { name: "quzye", weight: 64 },
  { name: "sbmrcz", weight: 63 },
  { name: "pxfxcwi", weight: 370, programs: ["ctglahh", "yofaj"] },
  { name: "ywjdepk", weight: 13 },
  { name: "payocx", weight: 70 },
  { name: "zvatf", weight: 151, programs: ["cejttl", "fhhim"] },
  { name: "bqozbpx", weight: 89 },
  { name: "zkkvo", weight: 120, programs: ["ndxlz", "nbpzp", "lzsao"] },
  { name: "gigyjrm", weight: 55 },
  { name: "avntwr", weight: 49 },
  { name: "rdpvd", weight: 17, programs: ["zhyhc", "tovzpw", "uuwxren"] },
  { name: "hdhay", weight: 88, programs: ["fvaow", "xjlyt"] },
  { name: "xmgiw", weight: 55 },
  { name: "wilmnmv", weight: 26, programs: ["bqdtj", "mjzkn", "gkjvxop"] },
  { name: "didaob", weight: 92, programs: ["zcnkvpn", "rrhqyi"] },
  { name: "ovlle", weight: 7 },
  { name: "lljlud", weight: 156, programs: ["hbhvg", "ynvqqj"] },
  { name: "gvangx", weight: 49 },
  { name: "npgsug", weight: 85 },
  { name: "swjbm", weight: 50 },
  { name: "nmqbvpq", weight: 18, programs: ["vwubn", "niuavpj"] },
  { name: "uxbkndn", weight: 74 },
  { name: "iyaxfqg", weight: 80 },
  { name: "sgamtw", weight: 1011, programs: ["jczlwrg", "bjbxg", "obxqu"] },
  { name: "lwjzn", weight: 205, programs: ["ojcor", "pkqwu", "jvamv"] },
  { name: "gofcp", weight: 21 },
  { name: "lmeql", weight: 8 },
  { name: "dqsam", weight: 325, programs: ["vjzteyv", "akbfb"] },
  { name: "sudoea", weight: 14 },
  { name: "ezbhdds", weight: 52, programs: ["njnaiiy", "rdjxdt"] },
  { name: "yfcqbsh", weight: 35 },
  { name: "axaojh", weight: 80 },
  { name: "ipgbw", weight: 1691, programs: ["fmnkdey", "arfng"] },
  { name: "sakar", weight: 6 },
  { name: "miimy", weight: 40 },
  { name: "rwnwac", weight: 71 },
  { name: "eiitagr", weight: 49 },
  { name: "azpiyc", weight: 19 },
  { name: "abdgd", weight: 748, programs: ["seygew", "rvqwfsn", "cslvss"] },
  { name: "zariy", weight: 23 },
  { name: "kwxszx", weight: 19 },
  { name: "auxqn", weight: 1005, programs: ["qaukdzx", "dzjhdt", "rhsppv", "farye", "jbttm", "rwcrct", "zsezyi"] },
  { name: "gxqhw", weight: 75, programs: ["qkruzdo", "uaqeuxd"] },
  { name: "atwydaw", weight: 106, programs: ["fsztlli", "swjbm", "orqxo", "eiajcj"] },
  { name: "qsidq", weight: 1554, programs: ["hmqyh", "xwclpv", "zkgbmgm", "tvxhhko"] },
  { name: "lftjq", weight: 85, programs: ["tuswre", "pdkxrqw"] },
  { name: "lgatvlk", weight: 134, programs: ["huozxzo", "ownte", "tgcmnm"] },
  { name: "vqzrfnp", weight: 43 },
  { name: "pkqwu", weight: 20 },
  { name: "xqsynow", weight: 83 },
  { name: "zlqcp", weight: 53 },
  { name: "bitvw", weight: 92 },
  { name: "ejasze", weight: 196, programs: ["aanhl", "rmgua"] },
  { name: "tmbndw", weight: 153, programs: ["xxohf", "csawtu"] },
  { name: "xnfff", weight: 1995, programs: ["dlqpyk", "yhwjhjq", "lmpji"] },
  { name: "cfourk", weight: 474, programs: ["hdefj", "bcslfkc", "imobzk", "ejasze"] },
  { name: "fntqeb", weight: 49 },
  { name: "eeuew", weight: 19 },
  { name: "jpoikof", weight: 77, programs: ["alkfw", "cwbnz"] },
  { name: "rxowzf", weight: 51 },
  { name: "lxmwuh", weight: 271, programs: ["wlwlu", "cfynk"] },
  { name: "wgwmd", weight: 51 },
  { name: "tfgkfd", weight: 31 },
  { name: "igbamrm", weight: 87 },
  { name: "sixatzk", weight: 217, programs: ["atuotwh", "wmiupn"] },
  { name: "dworfuk", weight: 6 },
  { name: "ngsbw", weight: 81 },
  { name: "cwkbizg", weight: 54 },
  { name: "gbqklts", weight: 76 },
  { name: "czxjike", weight: 27, programs: ["npgsug", "ammhz", "xakmmr", "pyentj"] },
  { name: "yvovprt", weight: 7 },
  { name: "zaulju", weight: 131, programs: ["bsaud", "xhrsff"] },
  { name: "phbuzyw", weight: 58 },
  { name: "hpkqdn", weight: 166, programs: ["kgxpfbq", "vgokyp"] },
  { name: "eqfuzz", weight: 70 },
  { name: "xddbpyw", weight: 57, programs: ["plnuv", "udebtlr", "fecfcyc"] },
  { name: "ycmcpqd", weight: 40 },
  { name: "azgcixi", weight: 58 },
  { name: "xatcr", weight: 211, programs: ["yfblca", "grnajbj", "tnmtz", "lampfo"] },
  { name: "diflt", weight: 273, programs: ["dzbqtuv", "pprqvx", "gmrgmk", "aqpxn"] },
  { name: "wswanrt", weight: 13 },
  { name: "gazra", weight: 248, programs: ["dlblhs", "ezpwfm"] },
  { name: "nlyrnm", weight: 84 },
  { name: "igrfqy", weight: 62 },
  { name: "jfshm", weight: 369, programs: ["crayus", "cmupq"] },
  { name: "ywexlv", weight: 18 },
  { name: "luoapw", weight: 18 },
  { name: "sgknjo", weight: 80, programs: ["qpism", "bfbjr", "vqrgyeu", "tzdhk", "xyebfi", "gbbqu", "rkddlwk"] },
  { name: "efoqm", weight: 88, programs: ["yrmfqoy", "gzfqvb"] },
  { name: "grrfq", weight: 86 },
  { name: "dwoad", weight: 58 },
  { name: "ssspogy", weight: 12 },
  { name: "arzanp", weight: 60 },
  { name: "kervui", weight: 212, programs: ["ovgheo", "quzye", "hmslvhd"] },
  { name: "xsmnbd", weight: 318, programs: ["tmbndw", "bdjhrqu", "grhiyhw", "mluvdn", "zzitpl", "ilcvskn"] },
  { name: "mywtvif", weight: 18 },
  { name: "nqlzz", weight: 125, programs: ["lwyux", "fnsflkm"] },
  { name: "hfwvb", weight: 51, programs: ["bvcujod", "wwunqd", "jkhfw"] },
  { name: "sptmayo", weight: 61 },
  { name: "crhzwz", weight: 58 },
  { name: "gisbvap", weight: 58 },
  { name: "cidcth", weight: 2400, programs: ["dwogs", "nnpbg"] },
  { name: "ywgvt", weight: 2102, programs: ["censvvb", "kiyra", "jjzna"] },
  { name: "wxrgtti", weight: 64, programs: ["dajhp", "demwz"] },
  { name: "boundtr", weight: 7 },
  { name: "cqvwrm", weight: 15 },
  { name: "wnqqem", weight: 205 },
  { name: "dvkfej", weight: 16 },
  { name: "dtkoit", weight: 37 },
  { name: "szirq", weight: 49 },
  { name: "hdbhw", weight: 128, programs: ["sakar", "dworfuk"] },
  { name: "imdjavh", weight: 35 },
  { name: "pqvvi", weight: 110, programs: ["yfcqbsh", "efomsfh", "ybayf", "hvlha"] },
  { name: "ooqtpgb", weight: 101, programs: ["nbtvxq", "eaayvc", "ilamw"] },
  { name: "yhohp", weight: 28 },
  { name: "znill", weight: 65 },
  { name: "bglby", weight: 69 },
  { name: "zkjxiqd", weight: 44 },
  { name: "oquxa", weight: 220 },
  { name: "qvgqro", weight: 128, programs: ["bqozbpx", "bjjyh"] },
  { name: "ncrxh", weight: 1679, programs: ["aptjif", "glwgh", "xddbpyw"] },
  { name: "jtbnzi", weight: 91, programs: ["gpkrbvt", "rhtin"] },
  { name: "nwtgwj", weight: 92 },
  { name: "iqyhxcw", weight: 40 },
  { name: "awcvbgl", weight: 76 },
  { name: "stktqgc", weight: 70 },
  { name: "qslsdtg", weight: 32 },
  { name: "nqrgm", weight: 32 },
  { name: "bdgcym", weight: 52 },
  { name: "ktfzzi", weight: 81 },
  { name: "obpbif", weight: 117, programs: ["fskdg", "yunufd", "bgute"] },
  { name: "sswubza", weight: 4286, programs: ["lcblh", "rjgycab", "dkyiz", "sochjt", "rgziu", "nqppb"] },
  { name: "dlqpyk", weight: 85, programs: ["kdqwwif", "cwkbizg"] },
  { name: "hptnh", weight: 22 },
  { name: "jtnbs", weight: 16 },
  { name: "xeaftl", weight: 50, programs: ["mvllqsx", "xmgiw"] },
  { name: "kfofavd", weight: 74 },
  { name: "unsssb", weight: 50 },
  { name: "hgvmyza", weight: 151, programs: ["oltfpgi", "xmkxjgq"] },
  { name: "mmtjv", weight: 91 },
  { name: "hsjgdl", weight: 59 },
  { name: "dchdrpf", weight: 51 },
  { name: "wypqz", weight: 48 },
  { name: "hibvd", weight: 58 },
  { name: "vaswfpp", weight: 21 },
  { name: "tgcmnm", weight: 89 },
  { name: "eiouio", weight: 19 },
  { name: "jcswni", weight: 150, programs: ["fswhx", "pxsjll"] },
  { name: "kjdboj", weight: 84 },
  { name: "wbked", weight: 19 },
  { name: "lwpjj", weight: 12 },
  { name: "wieeikb", weight: 14 },
  { name: "opbpuun", weight: 84 },
  { name: "gshbd", weight: 58 },
  { name: "rjgycab", weight: 1220, programs: ["cmwxozx", "bvtwdp"] },
  { name: "vpiug", weight: 131, programs: ["cweuc", "dtkoit"] },
  { name: "wrpla", weight: 11, programs: ["erxsplp", "szirq"] },
  { name: "kbdwm", weight: 13 },
  { name: "scbrb", weight: 77 },
  { name: "tukvj", weight: 91 },
  { name: "dkszj", weight: 1260, programs: ["bdjhzp", "ygqkwae", "pjmolr"] },
  { name: "bgwym", weight: 83, programs: ["qscxur", "gmxxgje"] },
  { name: "glwgh", weight: 300 },
  { name: "guzxauy", weight: 206, programs: ["ywigueo", "phpbf"] },
  { name: "exqzjfk", weight: 1075, programs: ["cbryc", "xjcadip", "zsdog", "rgsktf"] },
  { name: "xakmmr", weight: 85 },
  { name: "ccdvhvz", weight: 1616, programs: ["jolmd", "nthwie", "nsdmz", "lljlud"] },
  { name: "ydtdz", weight: 93 },
  { name: "zlkpb", weight: 366 },
  { name: "mdhmfy", weight: 97 },
  { name: "ubwbr", weight: 192, programs: ["adyaz", "phbuzyw", "vioxf"] },
  { name: "nnpbg", weight: 48 },
  { name: "qaybrra", weight: 60, programs: ["gjfmnpu", "kutxm", "kfnpyl", "ueeuim"] },
  { name: "ynvqqj", weight: 32 },
  { name: "mwrvamc", weight: 37 },
  { name: "dxbxbo", weight: 22 },
  { name: "ifuvb", weight: 83 },
  { name: "dkyiz", weight: 750, programs: ["jknlaad", "cqxfcqr", "iaxol", "pryxkzp"] },
  { name: "jrwro", weight: 125, programs: ["muvvc", "bitvw"] },
  { name: "cofbsq", weight: 48 },
  { name: "entepy", weight: 1294, programs: ["uzkekjp", "zaftnv", "yrsto"] },
  { name: "frmkl", weight: 41 },
  { name: "zaftnv", weight: 172, programs: ["ywexlv", "mywtvif"] },
  { name: "nneqad", weight: 83 },
  { name: "bjnxl", weight: 1974, programs: ["rdpvd", "tuvios", "uzuqqja", "dlfly", "hdbhw", "pbnqtmw"] },
  { name: "ygqkwae", weight: 248, programs: ["yodja", "tmrukz"] },
  { name: "nczykbr", weight: 62 },
  { name: "gvcmhx", weight: 177, programs: ["iuypybg", "blbjzdr"] },
  { name: "zzwgd", weight: 66 },
  { name: "vtxojlh", weight: 17 },
  { name: "ltzsoxk", weight: 238, programs: ["yjoghk", "zefog"] },
  { name: "xvapp", weight: 14, programs: ["adxktmm", "zlqcp", "tquiwoi", "idngwil"] },
  { name: "xfzbans", weight: 45 },
  { name: "lskwu", weight: 1466, programs: ["uxcmt", "ijxbxya", "mehhq"] },
  { name: "jhouok", weight: 56 },
  { name: "nwgqq", weight: 44 },
  { name: "ordnoxv", weight: 6 },
  { name: "alkfw", weight: 8 },
  { name: "uaqeuxd", weight: 17 },
  { name: "zdgotwb", weight: 61 },
  { name: "vxrjtk", weight: 60 },
  { name: "hciyw", weight: 68, programs: ["roecqp", "kmurcv", "wvzeiwz", "pidgo", "ipgbw"] },
  { name: "fskdg", weight: 51 },
  { name: "yjoghk", weight: 15 },
  { name: "ewjxaid", weight: 63 },
  { name: "hjfuq", weight: 42 },
  { name: "xcmjj", weight: 48 },
  { name: "ujrnrd", weight: 359, programs: ["vdaipmp", "jppbqj"] },
  { name: "upmfk", weight: 55 },
  { name: "srpls", weight: 63 },
  { name: "bjjyh", weight: 89 },
  { name: "fuzpme", weight: 72 },
  { name: "pbrakxw", weight: 27 },
  { name: "hlmune", weight: 5 },
  { name: "ozupxsh", weight: 10 },
  { name: "qytybg", weight: 48 },
  { name: "gwgodil", weight: 13 },
  { name: "uvamrg", weight: 9 },
  { name: "zaffbku", weight: 96 },
  { name: "cnoiggb", weight: 23, programs: ["eqfuzz", "stktqgc"] },
  { name: "eeznlcw", weight: 18 },
  { name: "ueeuim", weight: 25 },
  { name: "xomgh", weight: 6 },
  { name: "cdllr", weight: 7915, programs: ["xcxuhpd", "duwat", "mypyemv"] },
  { name: "kmurcv", weight: 81, programs: ["vjsezr", "gzwdr", "hztml", "vdspqsj", "iyylin", "ikjorey"] },
  { name: "scfmycd", weight: 88 },
  { name: "zfvnm", weight: 7 },
  { name: "oyfjp", weight: 63, programs: ["oypkcb", "xjljqp"] },
  { name: "dsxnt", weight: 83 },
  { name: "yrsto", weight: 86, programs: ["sptmayo", "czpmzex"] },
  { name: "bjcgvr", weight: 43 },
  { name: "pdkxrqw", weight: 86 },
  { name: "btkish", weight: 70 },
  { name: "akbfb", weight: 33 },
  { name: "fpgjkf", weight: 52 },
  { name: "qaukdzx", weight: 80, programs: ["qscii", "luedvgo"] },
  { name: "vopguxl", weight: 78, programs: ["mvhjvsx", "qrwrsw"] },
  { name: "fwvhiss", weight: 46, programs: ["mlqhbm", "naifggq", "xlezv", "amxwjmq"] },
  { name: "tuswre", weight: 86 },
  { name: "eqoivx", weight: 1680, programs: ["ezbhdds", "tfsenz", "leelb", "lgiwxh"] },
  { name: "dppnlm", weight: 84, programs: ["gwwrlp", "nkallms"] },
  { name: "xgdqc", weight: 93 },
  { name: "wsaugv", weight: 218, programs: ["eziybgr", "rujeuns"] },
  { name: "pprqvx", weight: 32 },
  { name: "volvsy", weight: 91 },
  { name: "zigvdka", weight: 35 },
  { name: "zygeve", weight: 67 },
  { name: "anykkx", weight: 85 },
  { name: "qposz", weight: 7 },
  { name: "tdocp", weight: 88 },
  { name: "quozn", weight: 33 },
  { name: "arfng", weight: 29 },
  { name: "farye", weight: 128, programs: ["lakdjt", "jbwvuqa", "luoapw"] },
  { name: "vsqpyrc", weight: 29 },
  { name: "njnaiiy", weight: 76 },
  { name: "hhyqt", weight: 403, programs: ["eeuew", "azpiyc"] },
  { name: "muewwty", weight: 45, programs: ["yfnxyuz", "xnasc", "lsepilv", "fkstubd"] },
  { name: "fvzkg", weight: 74 },
  { name: "ozqmk", weight: 88 },
  { name: "jvbywje", weight: 10 },
  { name: "bbyfznm", weight: 82 },
  { name: "lzjyxw", weight: 266 },
  { name: "vgokyp", weight: 42 },
  { name: "pohuglk", weight: 32 },
  { name: "dahggdi", weight: 19 },
  { name: "wqmly", weight: 67, programs: ["ucuhiy", "ngsbw", "cbato", "czqieu"] },
  { name: "itnagm", weight: 99 },
  { name: "hnovowe", weight: 2085, programs: ["cnoiggb", "vjabq", "pjmhz"] },
  { name: "nzxlkrf", weight: 43 },
  { name: "hwkclx", weight: 72 },
  { name: "vvdnnin", weight: 66 },
  { name: "orqxo", weight: 50 },
  { name: "cwqzpce", weight: 14 },
  { name: "iuypybg", weight: 40 },
  { name: "qhvtakl", weight: 108 },
  { name: "hyohkqq", weight: 81 },
  { name: "jmjxm", weight: 12 },
  { name: "bzqoi", weight: 103, programs: ["kqazfnj", "hpxuh", "rzriujy"] },
  { name: "zgikmp", weight: 33 },
  { name: "xjcadip", weight: 256, programs: ["mouemac", "tysys"] },
  { name: "rzriujy", weight: 45 },
  { name: "ymaow", weight: 89, programs: ["nafjxju", "cbsbti", "lxmwuh", "dqsam", "kmbky", "wqmly"] },
  { name: "lhjmsy", weight: 208, programs: ["tpacy", "eiouio"] },
  { name: "emsuiot", weight: 40 },
  { name: "xsbbpem", weight: 13 },
  { name: "uplvccb", weight: 62, programs: ["rmlqc", "tukvj"] },
  { name: "leelb", weight: 94, programs: ["gigyjrm", "upmfk"] },
  { name: "espnx", weight: 11107, programs: ["auxqn", "vcguzz", "cqokt"] },
  { name: "jihuf", weight: 19 },
  { name: "ryapaif", weight: 7 },
  { name: "jolmd", weight: 163, programs: ["dahggdi", "wbked", "xjweui"] },
  { name: "lwyux", weight: 77 },
  { name: "tpacy", weight: 19 },
  { name: "uzkekjp", weight: 124, programs: ["mkcrsy", "xawwkeu"] },
  { name: "sfnmpjd", weight: 74 },
  { name: "vxagjlw", weight: 58 },
  { name: "gmslbkd", weight: 71 },
  { name: "xwclpv", weight: 193, programs: ["lqpnpz", "rxocfu"] },
  { name: "vdspqsj", weight: 230, programs: ["mavhgq", "eknhj"] },
  { name: "fwxzdr", weight: 41 },
  { name: "njftjr", weight: 96 },
  { name: "dutblrl", weight: 212, programs: ["gdise", "boundtr"] },
  { name: "hekhmmx", weight: 287, programs: ["smkqkas", "owlxwub"] },
  { name: "pbnqtmw", weight: 68, programs: ["uxpdj", "hapofa", "qnyjwud", "eeznlcw"] },
  { name: "aqpxn", weight: 32 },
  { name: "vmpywg", weight: 7, programs: ["ykkcei", "azyzcr", "ywmuda", "ndjsvna"] },
  { name: "hlfmjm", weight: 86 },
  { name: "nofuzdd", weight: 14, programs: ["wwudvj", "fudnt", "ororw", "gshbd"] },
  { name: "cjxht", weight: 312 },
  { name: "kutcu", weight: 170, programs: ["tmrvz", "mwrvamc"] },
  { name: "fjahqnz", weight: 44 },
  { name: "fpart", weight: 85 },
  { name: "ffojoq", weight: 68 },
  { name: "phocz", weight: 5 },
  { name: "xyoog", weight: 7 },
  { name: "tbhokxb", weight: 222, programs: ["dwoad", "crhzwz"] },
  { name: "zuziby", weight: 61 },
  { name: "jjtsj", weight: 85 },
  { name: "mavhgq", weight: 24 },
  { name: "tpurix", weight: 21 },
  { name: "pwtps", weight: 42 },
  { name: "nbtvxq", weight: 26 },
  { name: "crdiqm", weight: 102, programs: ["enlerk", "mkaus"] },
  { name: "pxsjll", weight: 23 },
  { name: "nddyl", weight: 5976, programs: ["abdgd", "bqqmp", "oogodf", "cfourk", "nkuur"] },
  { name: "fagghhk", weight: 58 },
  { name: "fmnkdey", weight: 29 },
  { name: "uktjzbb", weight: 92 },
  { name: "ertegmg", weight: 48 },
  { name: "phpbf", weight: 31 },
  { name: "coxuj", weight: 85 },
  { name: "xfbrfa", weight: 84 },
  { name: "hbcnhi", weight: 7, programs: ["lzqmapb", "trkiub"] },
  { name: "tnmtz", weight: 26 },
]

function matchPrograms() {
  input.forEach((program, key) => {
    if(program !== undefined && program.programs !== undefined) {
      program.programs.forEach((progInProg, progKey) => {
        let programInInput = input.find((entry, key) => {
          let match = (entry.name == progInProg)
          if(match) {
            input[key].parent = program.name
          }
        })
      })
    }
  })
}

function hasNoParent() {
  let masterParent = input.find((program, key) => {
    return program.parent === undefined
  })
  return masterParent
}

matchPrograms()
console.log("1: masterParent:", hasNoParent())
