// Generated by CoffeeScript 1.9.2
(function() {
  var THEcounter, checkHash, counter, hash, hashed, key, md5, md5string, print, secretKey, start, startsWith;

  key = "bgvyzdsv";

  start = "000000";

  counter = 0;

  secretKey = 0;

  md5 = CryptoJS.MD5(secretKey);

  md5string = md5.toString();

  hash = function(key) {
    md5 = CryptoJS.MD5(secretKey);
    return md5.toString();
  };

  startsWith = function(string, start) {
    return string.substring(0, start.length) === start;
  };

  print = function(text) {
    return document.getElementById("result").innerHTML += "<br>" + text;
  };

  checkHash = function() {
    var THEcounter, hashed;
    counter++;
    secretKey = key + counter;
    hashed = hash(secretKey);
    if (startsWith(hashed, start)) {
      THEcounter = counter;
      return print("hashed for key " + key + counter + " is " + hashed);
    }
  };

  THEcounter = void 0;

  while (THEcounter === void 0) {
    counter++;
    secretKey = key + counter;
    hashed = hash(secretKey);
    if (startsWith(hashed, start)) {
      THEcounter = counter;
      print("hashed for key " + key + counter + " is " + hashed);
    }
  }

  print("loop done, last counter: " + counter);

}).call(this);
